### ISSUE TITLE
Stray link

### ISSUE THREAD

**Issue by tripleo1** [metaborg/stratego#39]
https://github.com/metaborg/stratego/blob/master/stratego.example/calc.str2

https://github.com/metaborg/stratego/blob/48346bbd203f03132128ebf20ed9bcdb3b193e82/stratego.example/calc.str2#L1

**Comment by Apanatshka** [comment]
Thanks for reporting 👍 
I did a search and it looks like that's the only stray link. I pulled the code from a listing of Toine's thesis, I believe it's the right one. So should be good now.
